### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [darcamo/covid19#1]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/E7TX0C
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by darcamo** [comment]
That is ok, but notice that the files added in the link you posted are only test files. They are from the actual data file and thus they have the same format, but they only contain a few lines in order to speeding-up the tests, since the purpose is to test the python functions that work with them.
